### PR TITLE
fix(reports): can "regenerate" a report the same day

### PR DESCRIPTION
**Pull request by mapreal19**

### CODE REVIEW

**Review by JKinnez — COMMENTED** [review]
Report can only be generated once a day? What happen if I do generate a dayli report and then I realize I forgot to set a Grade? I have to wait until next day? Or because it is diferrent It will generate a new one?

**Comment by mapreal19** [comment]
We can also delete the previous one if you want to regenerate multiple times per day

**Comment by mapreal19** [comment]
But it was a good question, we could have human errors when introducing grades and it could be useful to regenerate the report the same day. 

And we all know that guy who will go crying to the professor trying to get a 5 when having a 4.4

**Comment by AlejandroAdrian** [comment]
But what about the blockchain? Only the first one is stored in blockchain. If the teacher changes the mark, the report is not store in the blockchain.

Students will not be able to cry.

**Comment by mapreal19** [comment]
but we can create another transaction in blockchain. @serveba what happens if there was an error in grading and a teacher needs to regenerate the report?

**Comment by serveba** [comment]
The error will be certified also. 
In my opinion, if you have an older certified report, this will be the one who is the correct one.

**Pull request merged**
